# Generated by Django 5.0 on 2026-03-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_task_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='prioridade',
            field=models.CharField(choices=[(1, 'Baixa'), (2, 'Media'), (3, 'Alta')], default=1, max_length=5),
        ),
    ]
