# Generated by Django 5.0 on 2026-03-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_alter_task_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='prioridade',
            field=models.IntegerField(choices=[(1, 'Baixa'), (2, 'Media'), (3, 'Alta')], default=1),
        ),
    ]
